jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      schema: 'dev'
      threads: 4

    prod:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      schema: 'prod'
      threads: 4

    pr:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      # e.g., pr_123__abcdef; must match your build & teardown conventions
      schema: "{{ env_var('SCHEMA_PREFIX', 'pr') }}_{{ var('schema_id') }}"
      threads: 4
