name: CI schema teardown on PR close

on:
  pull_request:
    types: [closed]

concurrency:
  group: dbt-pr-teardown-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  CI_TEARDOWN_job:
    runs-on: ubuntu-latest

    env:
      # ❄️ Snowflake creds (add as repo secrets)
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}      # or key-pair; see note below
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}

      # Prefix used in your PR schemas, e.g. pr_123__<sha>  → SCHEMA_PREFIX=pr
      SCHEMA_PREFIX: pr
      DBT_TARGET: pr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (dbt-snowflake)
        # Ensure dbt-requirements.txt includes dbt-snowflake==1.8.*
        run: pip install -r dbt-requirements.txt

      - name: Capture PR number
        run: echo "PR_NUM=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: dbt deps
        run: dbt deps --target $DBT_TARGET

      - name: Drop PR schemas in Snowflake
        run: >
          dbt run-operation drop_pr_schemas
          --target $DBT_TARGET
          --args '{"database": "'"$SNOWFLAKE_DATABASE"'",
                  "schema_prefix": "'"$SCHEMA_PREFIX"'",
                  "pr_number": "'"$PR_NUM"'"}'
